### ISSUE TITLE
Doc link is dead

### ISSUE THREAD

**Issue by shobitb** [thunderbiscuit/devkit-wallet#9]
On the README page (`simple-wallet` branch), it says: "You can find the companion tutorial website for this repository [here](https://thunderbiscuit.github.io/bitcoindevkit-android-sample-app/)"

but that link is a dead link.  I get a 404 Not Found page.

The correct link, I think, is https://thunderbiscuit.github.io/devkit-wallet/

**Comment by thunderbiscuit** [comment]
Good catch! Mind opening a PR for it?

**Comment by thunderbiscuit** [comment]
Thanks @shobitb!
